# Generated by Django 3.2 on 2021-04-11 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeffcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reg_no',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[A-Z0-9]*$', 'Only valid register numbers are allowed')]),
        ),
    ]
