# Generated by Django 3.1.7 on 2021-04-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeffcs', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='profile',
            name='status_value',
            field=models.IntegerField(default=0),
        ),
    ]
